#!/bin/sh

if [ -e /Library/LaunchAgents/com.crunchy.tuiomousedriver.plist ];then
	sudo -u $loggedInUser /bin/launchctl unload /Library/LaunchAgents/com.crunchy.tuiomousedriver.plist
	mkdir -p /tmp/tuiomousedriver/backup/
	mv /Library/LaunchAgents/com.crunchy.tuiomousedriver.plist /tmp/tuiomousedriver/backup/
fi

pkill -9 TuioMouse.jar

if [ -e /Applications/Utilities/TuioMouse.jar ];then
	rm -f /Applications/Utilities/TuioMouse.jar
fi